"""empty message

Revision ID: 13f27b88ba79
Revises: 
Create Date: 2023-01-17 09:18:45.063154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13f27b88ba79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('average_earning', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('Student', 'Volunteer', name='user_category_enum_ct'), nullable=False),
    sa.Column('math', sa.Float(), nullable=False),
    sa.Column('physics', sa.Float(), nullable=False),
    sa.Column('chemistry', sa.Float(), nullable=False),
    sa.Column('biology', sa.Float(), nullable=False),
    sa.Column('literature', sa.Float(), nullable=False),
    sa.Column('history', sa.Float(), nullable=False),
    sa.Column('geography', sa.Float(), nullable=False),
    sa.Column('phylosophy', sa.Float(), nullable=False),
    sa.Column('art', sa.Float(), nullable=False),
    sa.Column('foreign_language', sa.Float(), nullable=False),
    sa.CheckConstraint('art>=0 AND art<=10'),
    sa.CheckConstraint('biology>=0 AND biology<=10'),
    sa.CheckConstraint('chemistry>=0 AND chemistry<=10'),
    sa.CheckConstraint('foreign_language>=0 AND foreign_language<=10'),
    sa.CheckConstraint('geography>=0 AND geography<=10'),
    sa.CheckConstraint('history>=0 AND history<=10'),
    sa.CheckConstraint('literature>=0 AND literature<=10'),
    sa.CheckConstraint('math>=0 AND math<=10'),
    sa.CheckConstraint('phylosophy>=0 AND phylosophy<=10'),
    sa.CheckConstraint('physics>=0 AND physics<=10'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_job',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_job')
    op.drop_table('user')
    op.drop_table('job')
    # ### end Alembic commands ###
