"""empty message

Revision ID: 7490b2f83351
Revises: 
Create Date: 2023-01-16 00:31:47.132498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7490b2f83351'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('average_earning', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('Student', 'Volunteer', name='user_category_enum'), nullable=False),
    sa.Column('math', sa.Float(), nullable=False),
    sa.Column('physics', sa.Float(), nullable=False),
    sa.Column('chemistry', sa.Float(), nullable=False),
    sa.Column('biology', sa.Float(), nullable=False),
    sa.Column('literature', sa.Float(), nullable=False),
    sa.Column('history', sa.Float(), nullable=False),
    sa.Column('geography', sa.Float(), nullable=False),
    sa.Column('phylosophy', sa.Float(), nullable=False),
    sa.Column('art', sa.Float(), nullable=False),
    sa.Column('foreign_language', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_job',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_job')
    op.drop_table('user')
    op.drop_table('job')
    # ### end Alembic commands ###
